---

- name: prepare host to update vbox-guest-additions
  hosts: all
  become: true
  vars:
    upgrade: True
  tasks:
    - name: update all packages..
      apt:
        update_cache: True
        upgrade: dist
      when: upgrade | bool

    - name: install required packages
      apt:
        name:
          - build-essential
          - linux-headers-{{ ansible_kernel }}

    - name: debug
      debug:
        var: ansible_kernel

# shutdown vm
# add cdrom-drive and insert guest-additions iso
# start vm
# mount /dev/cdrom /mnt
# sudo sh /mnt/VBox...

