---

- name: Do something with ceph nodes
  hosts: all
  remote_user: adu
  become_method: sudo
  become: true
  vars:
    pve_repo:
      url: "http://download.proxmox.com/debian/pve"
      gpg_url: "https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg"

  tasks:

    - name: fix /etc/hosts to contain ip-address
      ansible.builtin.copy:
        content: |
          127.0.0.1	localhost
          {{ ansible_facts.eth1.ipv4.address }} {{ ansible_facts.hostname }}.home.fgdo.de {{ ansible_facts.hostname }}

          ::1		localhost ip6-localhost ip6-loopback
          ff02::1		ip6-allnodes
          ff02::2		ip6-allrouters
        owner: root
        group: root
        mode: 0644
        dest: /etc/hosts

    - name: install required packages... sigh
      ansible.builtin.apt:
        name:
         - gnupg2

    # create apt repo file
    - name: add pve apt repo gpg key
      ansible.builtin.apt_key:
        url: "{{ pve_repo.gpg_url }}"
        state: present

    - name: Create pve apt repo
      copy:
        dest: /etc/apt/sources.list.d/pve-install-repo.list
        mode: 0644
        owner: root
        group: root
        content: |
          deb [arch=amd64] {{ pve_repo.url }} bullseye pve-no-subscription
      register: apt_repo

    # update apt if last task was changed (not as handler because it is required right here)
    - name: update apt caches # noqa no-handler
      apt:
        update_cache: True
      when: apt_repo is changed

    - name: upgrade apt
      apt:
        upgrade: dist

# https://forum.proxmox.com/threads/debian-11-to-proxmox-7-problems.96477/
# Lösung soll hier sein `apt-mark hold ifupdown2` vorher auszuführen...
    # - name: hold ifupdown2
    #   dpkg_selections:
    #     name: ifupdown2
    #     selection: hold
    - name: hold ifupdown2
      ansible.builtin.command:
        cmd: apt-mark hold ifupdown2

    - name: install required packages
      ansible.builtin.apt:
        name:
         - postfix
         - open-iscsi

    - name: install proxmox VE packages tools
      apt:
        state: present
        name:
          - proxmox-ve

    - name: disable enterprise repository for this test!
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        line: "# deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise"
        state: present
        regex: "(?:^\\s*|^#\\s*|^deb).*pve-enterprise$"


    # -name: configure postfix to only local...

